pystardust/ani-cli

- README.md
- ani-cli
> feat: episode count to continue where we left off

- ani-cli
I made this to fix an issue when leaving the player open for so long, the m3u8 URL got expired and I had to open the next episode and get back to the one I was watching, so with this PR we can easily replay the current episode without all the headache
> add option (r) to replay current episode

- ani-cli
No need to hardcode the referer header
> fix: Referer header

- ani-cli
Simple fix as suggested
Issue #99
> Fixed out of range ep loading on second try

- README.md
- ani-cli
Fixed the download feature
There is an extra dependency (ffmpeg)
> fix: download feature

- README.md
- ani-cli
I added this option for the user to choose which anime to delete from the history.
Using the `-D` option
> New delete history option.

- ani-cli
Skips checking for mpv if user is only downloading
> Allow download without install media player

- ani-cli
Video quality selecting now working again with the new updates
> Updated get_links and fixed get_video_quality function

- Makefile
- README.md
- ani-cli
Updated ani-cli to check if the local repo is up to date with the remote repo on script start up. Included a message to be echo'd when an update is available or the local branch has become diverged.
Here's a nifty SO that explains the git syntax - https://stackoverflow.com/a/3278427/16004619
Added git to required dependencies in README.md and dep_ch method.
> Inform user if update is available. Includes instuctions on how to update. Added Git to dependencies.

- ani-cli
Add scraping for recent anime on main gogoanime page and selecting from these scraped.
Also fixed slight "--dub" misalignment.
> Add scraping for recent anime

- ani-cli
Fix for issue #240, may need more links of anime with special characters to test out to ensure its 100% working
> Fix bug on searching anime with special character

- ani-cli
> Output error message for animes with no uploaded episodes yet

- ani-cli
> Replace ffmpeg with curl

- README.md
- ani-cli
Changed the video link to sbplay.. for faster downloading and streaming
updated quality selection options..
the PR addresses.. vlc cannot open link, streaming is slow, video quality selection issues...
@ura43 please tag them here..
> scraping sbplay for downloading and streaming

- ani-cli
@ura43 maybe this fixes your problem...
And I tried it in dash.. and it was working there fine..
> normal quality doesn't exist

- ani-cli
Should be a simple fix for issue #334, #323, etc.
> Added a simple check for a null $video_url

- README.md
- ani-cli
> switched to vidcdn

- README.md
- ani-cli
I think we should add jq as dependency.. because conventional method doesn't work on old anime properly... 
I hope this fixes problem..
And I know this could be adding another program as dependency.. but its worth it..
> added jq as dependency again

- README.md
- ani-cli
I added a version number for reference to see which practical version is used in case of a bug, so misconception are more unlikely to accrue
> Add version number

- Makefile
- README.md
> android termux

- .github/workflows/master.yml
- CONTRIBUTING.md
- README.md
- ani-cli
- disclaimer.md
> Reduce scope, expand Linting

- README.md
I have made another PR for the android-termux branch if you'd all like to check out (for some reason I cannot submit one PR for two different branches).
https://github.com/pystardust/ani-cli/pull/374
> Add Android Support to the README

- ani-cli
1) Made so that if the script fails to update for some reason, it
will tell the user
2) Fixed a bug which won't print version if an argument isn't
provided
3) Made so that the program will only try to get the url if
neccessary(E.G. not when the user prints the help menu)
** EXTRA DEPENDENCY ADDED(TAC)**
4) Made so that history will be shown reverse so the last seen anime
will be at the top
5) Made so that if an anime is watched with it already being on the
history, the script will delete the line and append to the end
> Some bugfixes and a new feature

- ani-cli
fixed the issue #377 , along with interface not showing for those having nohup version > 8.3
> fixed app closed on invalid option in ep interface

- Makefile
- README.md
- ani-cli
Because maintaining multiple branches sucks way harder than a non-trivial makefile
> Unite the branches

- ani-cli
> Fix #369 bug

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/enhancement.md
- .github/ISSUE_TEMPLATE/feature_request.md
> Add more Issue Templates

- README.md
- ani-cli
Replace jq with more conventional parsing #413
> Replacing jq with regex

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/enhancement.md
- .github/ISSUE_TEMPLATE/feature_request.md
This is as good as it will get. 
Follow up commit not unlikely, since I can't preview unless on master
> markdownlint the templates

- README.md
- ani-cli
It cannot accept a range of episodes at this point and settings subs is not supported cause I cannot find any thing in the script about that.
> Fix #389 and #422

- ani-cli
There was a small bug when you the video player closed at last episode of the auto play range, where the "Currently playing" message got displayed twice.
> Small bug introduced with auto play

- ani-cli
> Fix grep: invalid repetition count(s) regex bug

- CONTRIBUTING.md
> Update: adding test idea for old anime.

- CONTRIBUTING.md
> update: shellcheck rule

- README.md
- ani-cli
if you specify the range: 1 -1 it will automatically set the last ep in the range to the last ep in the anime
> added so you can select all episodes when you select a range

- ani-cli
organize code into function and adding exit and search another anime option into search anime menu.
> fix: Adding exit option in search anime menu

- ani-cli
> Fix Ani-cli breaks pywal set terminal colors 

- ani-cli
> Fix invalid number entered bug in history menu

- README.md
> New Readme head

- ani-cli
Dang, this should be in the v1.7 release. 
Clicked release a second to soon :sweat_smile:
> chore: bump version v1.6.7 -> v1.7.0

- ani-cli
> fix: ani-cli not able to create history file if history dir doesnt exist

- ani-cli
just bumped the version to 1.8
> new release

- ani-cli
Print options when user select anime quality.
> Show options for video qualities.

- ani-cli
> Fix incompatibility with zsh

- README.md
- ani-cli
echo is required in line 177 to create padding in new_id variable.. if someone else have a better solution can clone my repo and fix it..
> fix: new decrypt function, script working again

- ani-cli
> Fix: New keys and IVs in GogoAnime

- README.md
- hist_transition.sh
small temporary script to update those old history files. 90% of time it works every time.
> Feature: tool for updating history file

- ani-cli
Same as #609 which was closed after v2 was merged
> Move play-episode to separate function

- .github/ISSUE_TEMPLATE/bug-report.md
- README.md
This appears to have been lost along the way to v2
> reintroduce version metadata to issue template

- CONTRIBUTING.md
- README.md
My two goals with this rewrite are being more welcoming to new contributors and documenting our test procedure
> CONTRIBUTING.md rewrite

- README.md
Updated Mac OS installation instructions, I don't think a homebrew tap is necessary, and with all of the recent changes gogo  has made to their to their keys, it just makes more sense to install directly from source, instead of through latest releases
PS: please ignore the number of commits, i was doing some choking activity
> docs: Mac OS installation

- ani-cli
> fix: exit if cannot connect to internet

- ani-cli
> feat: ani-sync -s arg

- ani-cli
PR for alternate links parsing and also fixing "auto" bug
> Feat: Alternate links

- ani-cli
> fix:same ep fetching

- ani-cli
> fix:long access times

- README.md
- ani-cli
Tested with a Windows User, works as expected
> feat: ani-sync on windows

- README.md
> docs: termux mpv referrer

- README.md
Fix for https://github.com/pystardust/ani-cli/issues/735
> [issue 735] - Update README.md

- README.md
keeping up to date with master
> docs: android referrer and pkg up

- ani-cli
- players/player_download
> fix : new search engine

- bin/ani-cli
- hist_transition.sh
With lots of choking... finally updated the hist_transition script...
> Hist patch

- bin/ani-cli
> Chore: fix

- README.md
- bin/ani-cli
- lib/ani-cli/UI
- lib/ani-cli/player_iina
- lib/ani-cli/player_mpv
- lib/ani-cli/player_vlc
- no weird space in episode selection
- if during anime selection user just presses enter, then select first anime
- if during episode selection user just presses enter, then select last episode
*ramble here*
> feat: minor UX improvements

- .github/workflows/master.yml
- ani-cli
> fix:playing on android

- .github/workflows/master.yml
- ani-cli
> fix: double search

- README.md
- Remove RayGL and 71zenith as maintainers due to extended vacancy
- Add lobster to the homies section
> docs: lobster homie & retired maintainers

- README.md
[mangal](https://github.com/metafates/mangal) added. Download & read manga from __any__ source with Anilist sync (Go)
> Can I be a homie? 🤓🤓

- ani-cli
> fix: reduce axel connections 30 -> 10

- README.md
- ani-cli
> some fixes

- ani-cli
> chore: bump version v3.3.5 -> v3.4.0

- ani-cli
> fix: -h exits with exit code 0

- ani-cli
solves #881 
Exits the program once user presses enter after the last available episode is completed
> Exit on last ep completion on enter

- ani-cli
*rumbling, rumbling oh the rumbling*
> fix: api/live -> api/cW9

- ani-cli
QoL feature for steam deck users: mpv from Flathub(Discovery) can be used now.
[x] Lain
[x] The safe bet: One Piece
[x] Episode 0: Saenai Heroine no Sodatekata ♭
[x] Unicode: Saenai Heroine no Sodatekata ♭
[] Not uploaded: one piece dub episode 590
[x] Unreleased: soredemo ayumu wa yosetekuru (already released)
[x] Short id (for decryption): Log Horizon episode 1-2
> V4 steamdeck

- ani-cli
> literal . in grep

- README.md
Remove (work in progress) from mov-cli mention
> Remove (work in progress) from mov-cli mention

- ani-cli
- ani-cli.1
How embarrassing for me to forget this
> chore: bump version v4.0.4 -> v4.0.5

- ani-cli
```
_____.___..__  __                     
\__  |   ||__||  | __  ____    ______ 
/   |   ||  ||  |/ /_/ __ \  /  ___/ 
\____   ||  ||    < \  ___/  \___ \  
/ ______||__||__|_ \ \___  >/____  > 
\/                \/     \/      \/  
```
> fix: set executable bit again

- README.md
- ani-cli
> switch to curl

- ani-cli
> fix: connection error (#1039)

- README.md
> docs: update demo video

- README.md
> added debian instructions

- README.md
> docs: prune and reorder homies

- README.md
Fixed table of contents Debian link.
#1076
> docs: fixed debian table of contents link

- README.md
> docs: highlight possible curl issues (windows)

- ani-cli
> fix: some m3u8 downloads were broken

- README.md
- ani-cli
> iOS Download support

- README.md
> added hyperlink to respective OS from badges in README.md

- .github/workflows/ani-cli.yml
- .github/workflows/version.yml
pls merge asap.
version check on master will always return false, since it will git diff with itself, thus no bumped version detected.
I extracted that check into a separate file that runs only on PR
> test: no version test on master push

- .github/workflows/inverse-ani.yml
- .github/workflows/inverse-md.yml
- .github/workflows/inverse.yml
- .github/workflows/markdown.yml
- .github/workflows/title.yml
Fix for [conditional but required jobs](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/troubleshooting-required-status-checks#handling-skipped-but-required-checks)
> test: create inverse jobs to catch required conditionals

- ani-cli
> feat: refactor code and optional hls script

- ani-cli
fix: remove problematic provider (rab)
fix: accidental skipping of links
*ramble here*
---
---
> fix: tmp outage (#1196)

- ani-cli
> refactor: extra space in help

- .github/CODEOWNERS
docs/community manager -> justchokingaround
code review -> port19x & derisis13
> test: bump codeowners file

- README.md
Literally just that (i know it sounds silly :turtle:)
> docs: homies section saiku -> dantotsu

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
> docs: simplify docs

- README.md
> docs: add doccli to homies

- README.md
* Documentation update
add goanime to homies
> docs: add goanime to homies 

- README.md
iSH downloads are slow. A `git clone --depth 1` speeds up the installation process.
---
---
> docs: expedite ani-cli iOS installation

- README.md
> docs: add ykhan21 as a maintainer

- README.md
Updated windows instruction to remove the duplicate windows terminal install commands and replace with command to install ani-cli.
> docs: update windows installation documentation

- .github/workflows/ani-cli.yml
> ci: shellcheck completion file annoyance

- README.md
This is a tool i made inspired from Jerry which uses ani-cli providers and does all the anilist requests, Skips Intro and Outro, Discord RPC and many more features.
> docs: add Curd to homies

- README.md
I rewrote the program in Golang. Sorry for the recurring pull requests.
> docs: Update homies (Curd) detail
