pystardust/ani-cli

- ani-cli
Previously, when you control c in the script, the shell will start to be displayed in green. This echos the reset color code when there is a keyboard interrupt.
> Reset shell color when exiting via keyboard interrupt

- ani-cli
Instead of getting 3 options, next episode, previous episode and exit, we now get a fourth option to select any episode. It really bugged me that we can only go to next or previous episode so I added this feature.
```
[n] next episode
[p] previous episode
[s] select episode
[q] exit
Enter choice: s
Choose episode [1-11]: 4
Getting data for episode 4
```
> Added option to select episode with next and previous episode.

- README.md
- ani-cli
For some animes, such as Attack on Titan season 3, or Tokyo Revengers, playing the url through `mpv` throws a `[ytdl_hook] ERROR: Unsupported URL: https://yare3.yare.wtf/vidstreaming/animefrenzy/.....` error, as described in  [Issue #22 of master branch](https://github.com/pystardust/ani-cli/issues/22#issue-937292919).
If that happens, then playing the url through `xdg-open` results in the video directly being opened from a browser. Then the anime is watchable again. 
However, `xdg-open` will always open the url through the browser, so it cannot replace `mpv.`
Which is why it is kept as an option if `mpv` fails.
> Error handling for: `[ytdl_hook] ERROR: Unsupported URL`

- ani-cli
The previous pull request did fix [the error](https://github.com/pystardust/ani-cli/issues/22). **However,** the dubbed version of the episode opened, instead of the subbed version that one would normally expect (as nowhere in the name there is any mention of this being the dub).
After investigating the `curl` output in the `play_ep` function, and also visiting 9anim.vip myself, I realised that there were two links being given with the same "Download" button, one with the subbed episode and the other one being the dubbed. The script cannot distinguish between the two, and as a result *always* ends up picking the dubbed version (updating the `url` variable with the dubbed link) and never the subbed one, as the script goes through the curl output line by line.
The dubbed link is always a …
> Fix: subbed version not opening for some animes, going for the dub instead

- README.md
- ani-cli
I had this annoyance with your script that I need to relaunch it if I wish to watch another series.
To solve this I created a new option to the main loop: entering "a" will now bring up the search anime again. (I used cyan, because I don't know the reason for the original colour choices. Change it if you feel like so.)
I copied the code that runs on startup (query mode) since I don't understand the script that well. There might be better ways to do it, but this appears to work just fine.
It would make sense to make a function for those four lines, but I couldn't come up with an intuitive enough name for them. It shouldn't take more than a minute though.
I have tested my modifications myself, but I think an independent test would be appropriate to ensure I didn't break the script.
> Added the possibility to search for another anime in the main loop

- ani-cli
Just like the `a` option in the "menu" can run a query from gogoanime, the new `h` option lists what is in your history file.
Also includes the fix for #139 as suggested by @Dink4n 
I also touched the colour of the `a` option to make it an uniform yellow-magenta theme (it didn't really come trough when I wrote that part originally)
I'm also wondering whether the double semicolons do anything after the continue statements. If they don't should they be removed for decreasing file size and making the code simpler?
> History in loop

- ani-cli-win
this PR updates ``base_url="https://gogoanime.cm"`` to ``base_url="https://ww1.gogoanime.cm"`` on the windows-vlc branch as it is using the old domain.
>  gogoanime domain change on windows-vlc branch

- ani-cli
Uses a somewhat obscure `--adaptive-use-access` tag, which allows VLC to pass the Referer header to all chunks of the video. It doesn't work without it.
Implements a switch statement to possibly add support for some other media players in the future more easily
> Adds vlc support

- ani-cli
This way we can avoid having to hardcode a new base_url every time the domain moves, since they keep the old domains as redirects.
Invokes `curl` once, but may take a bit longer to resolve since it's, well, _resolving_. I used long options here for clarity, but the short ones appear to work as well.
> Auto-resolve $base_url

- ani-cli
Trace gogoanime's base url "https://gogoanime.cm" redirects and getting the final url from redirect as base_url value
> Fix base_url and Fix for video not able to play or download

- ani-cli
Just tested the script a bunch of times and found a regex bug, updated error messages for both vlc and mpv using status code
> Fix regex bug for gogoplay1 link

- ani-cli
This could be done by either adding the `-e` flag to echo or using `printf`, but I decided to go with the latter, since its used predominantly throughout the rest of the script.
Previously e.g. [line 260](https://github.com/pystardust/ani-cli/pull/239/files#diff-194f14a8c6649316c12fa9d712dd46d7f2424da13786e02de699144517efc3a6L260) would result in the output `\033[1;32m\nVideo played` instead of green formatting for the text.
> Fix color formatting on some status messages

- ani-cli
`setsid` is the only reason this doesn't work on Mac. 
If we replace it with `nohup`, it works perfectly on MacOS.
> Replace setsid with nohup for mac compatibility

- Makefile
I changed `cp` for `ln -sr`, which creates a relative symbolic link instead of a copy. 
With `cp` it's necessary to run `make install` after pulling and it's possible to have different versions of the script in the repo folder and `usr/local/bin/`.
The symbolic links only needs to be done once and it will make unnecessary to execute `make install` after every update, since any changes to the repo file will affect the one in `usr/local/bin` as well.
> Change copy to symlink in Makefile

- ani-cli
As seen in some issues some people want to specify the download directory (which would be rather useful if downloads where working...) in this patch I added the ability to specify the download directory via the option -p (standing for path).
I didn't put it as the $optarg for -d as that seemed rather annoying for those that don't need it.
> Added flag for specifying download directory

- ani-cli
The history file (logfile) should not be updated, when the "Cannot reach servers" issue is reported. Only update the history file when the video is playing.
> fix: only update history when video could be played

- ani-cli
curl used the function names "get_links" and "get_video_quality" as url. Seen in these warnings from my proxy setup:
```
[proxychains] Strict chain  ...  <my_proxy>  ...  get_links:80 <--socket error or timeout!
[proxychains] Strict chain  ...  <my_proxy>  ...  gogoplay1.com:443  ...  OK
[proxychains] Strict chain  ...  <my_proxy>  ...  get_video_quality:80 <--socket error or timeout!
```
> fix: url checks checking not an url

- ani-cli
This short statement is pretty convenient in my opinion when trying to switch between episodes. I used `pgrep` to check if the process of `mpv` or `vlc` is still running.
> Stop current episode from continuously playing when switching between episodes.

- ani-cli
Interrupting (ctrl+c) during a prompt did not quit immediately, but caused error messages due to invalid input.
Especially when interrupting the `get_search_query`, a invalid search request was sent to the website.
> fix: interrupt signal didn't quit

- README.md
- ani-cli
As we know that, gogoanime enabled referer link for downloading... we now get reduced speed.. like 400-600 KBps... Now we can use parallel downloading of aria2... to get above 1-2 MBps speed..
@Dink4n @ura43 you can try it with or without aria2.. by checking any episode..
note:- some download links ends at "==" or "=" .. they are little slower than the links ending at "alphabet" or "numeric"... In my testing...
> Replace curl with aria2

- ani-cli-win
http-referrer option fixes 304 error
vlc://quit URL adds VLC quit action to its playlist, so the VLC process can automatically close after the episode ends
> added VLC http-referrer option & automatically close VLC after playback

- README.md
- ani-cli
This snipet will allow you to update your ani-cli instance automatically
for _**future releases only**_
It's pretty handy for people who have their ani-cli inside `.local/bin` or something like that
Edit: Someone could say
>You could just symlink ani-cli from the git repo
But i think this make the script more usefull for people who only want to update without messing with git
> Feature add: update script

- ani-cli-win
Improvements added:
- Added ajax code matching current linux master
- updated download code to use aria2c if user's got it on their path but if they don't it'll use curl
- Filters out .vtt files that sometimes show up in the list of download links
Limitations:
From my limited testing it still gets the odd 403 errors with some series and settings but not others:
- Fine for the FLCL dubs but not subs
- Fine for Serial Experiments Lain but not Legend of the Galactic Heroes
But with this it once again plays _many_ things as opposed to _no_ things. If these bugs also exist in linux version this'll get windows users back to that level of access.
> Incorporated vidcdn updates

- README.md
- ani-cli
This allowed iina to work for me
> Support for more players and removal of ampersands

- .github/workflows/master.yml
- README.md
- ani-cli
~`-k` should become more consistent and maybe even default behaviour *(rewrite)*~
~`-p` should really be an optional arg for `-d` **(remove)**~
~`-v` should allow choice in any non-default video player as optarg, with vlc staying the default alternative.~
As always this tasklist is subject to change
> Improve UX and slim down

- README.md
`termux open --content-type video `
command not working perfectly instead of it `termux-open` works without specifying the content type . 
And it opens video player automatically when the link was video
> Changed installation steps for termux

- README.md
> Update README for Windows installation

- ani-cli
See [the issue description](https://github.com/pystardust/ani-cli/issues/491#issuecomment-1030709648) for more info
> Fixes for bug #491

- README.md
using 'am start' again due to termux-open having different problems in different devices
> docs: updating termux installation, now works with both mpv and vlc (-v option)

- README.md
- ani-cli
> fix : link parsing problems and reduce curl call for majority of animes

- README.md
Adds a warning about having an older, manually installed, version of ani-cli. Executables in `/usr/local/bin` can have precedence over those in `/opt/homebrew/bin`, meaning that users would continue using the older version, despite having the newer version installed.
> Add old version warning for macOS

- ani-cli
While playing episodes following error is printed to stderr:
dunno the exact reason but maybe cuz the background job finishes or smth but shell var ``$!`` should at least be able to record the PID of the recently executed job.instead null is returned.well whatever.btw i reccom using string comparison instead of int for all shell vars cuz we don't always get wat we want cuz itzzz **Shell scripting**.
if anyone has a fix to null returned PID,please do edit the pr.
> Fix: Fix comparison with null returned ``PID``

- ani-cli
I noticed that whenever I try to select the last episode by passing in "-1" it wouldn't work and thought that was odd. Went through the code and figured it was because it only works if you pass in a range of episodes. I want to be able to quickly select the last episode and thought others may have thought the same. Just two simple lines added using an established method, no idea why there's that third line deleted and added.
> be able to select last episode only(without a range)

- CONTRIBUTING.md
- README.md
- ani-cli
> feat: m3u8 parsing for quality selection,auto-update base-url, optimizations

- ani-cli
Forgot to check for version bump in previous merge, sorry
> chore: bump version 2.1.4 -> 2.1.5

- README.md
I've been maintaining the ani-cli NUR (nix user repository) packaged ani-cli for a little while now, since noticing that a section in the readme exists for installation instructions, I'm offering up this update to the readme in case the maintainers are interested in mentioning its availability on Nix.
> Add packaging status section to readme

- bin/ani-cli
Menu options were not appearing due to an if statement that checked if "select_first" was empty. Hopefully not needed.
> Menu options for history

- README.md
- bin/ani-cli
- lib/ani-cli/player_download
Supports multi-threading and is lighter and loads faster than, aria2.
> Switched to axel as the anime downloader.

- ani-cli
- [ x] Bug fix
*ramble here*
- [ x] any anime playing
- [ x] next, prev and replay work
- [ x] quality works
- [ x] downloads work
- [ x] quality works with downloads
- [ x] select episode -a and rapid resume work
- [ x] syncplay -s works
- [ x] autoplay, aka range selection, works
> fix: redirect stdout for syncplay

- README.md
We need to test for the lowest point release that still works for at least some anime and use that as our minversion for the badge. 
That would clearly indicate what native packages are hard broken and differenciate them from those that are merely outdated
> docs: add repology badge minversion

- ani-cli
ani-cli currently displays the error "No search results found" when searching for an anime. It turns out the reason for this issue is that the domain name used, "https://gogoanime.lu" is no longer valid. Instead it tries to redirect you to a new domain, "https://gogoanime.dk". This new domain is now used in this bug fix.
> fix: search gogoanime with updated url

- ani-cli
The current order for scraping is: 1: Xstreamcdn, 2: Animixplay, 3: Gogoanime. I'm sure there was a reason why we decided on this order, but recently Xstreamcdn has some hickups: it gets very slow sometimes. It can be an intentional throttle or a 'natural' server overload. A quick and dirty solution is to rank it one lower, maybe even two.
> Provider priorities

- ani-cli
Fixes issue #901.
This occurs because we are passing `selection_id` as is to `grep`.
Normally this wouldn't be an issue, except where the `selection_id` starts with `-` (_eg_, -code-geass-lelouch-of-the-rebellion-r2`).
Then `grep` would treat it as flags, causing the error.
> fix: grep error when selection_id starts with '-'

- ani-cli
busybox base64 doesn't support gnu style long options
> fix: drop gnu style long options on base64

- ani-cli
> fix: missing check for fzf

- ani-cli
refactor: grep by line number for accuracy
chore: v4.0.0 -> v4.0.1
*ramble here*
---
---
> fix: .5 episodes

- ani-cli
> spellcheck, it's history not histroy

- ani-cli
> fix: revert to 4.0.1

- ani-cli
- ani-cli.1
> fix: cut posix compliance

- README.md
In the Install section of the readme an info about the change of wget to wget2 for the debian package was added.
That change was made because it makes the install process easier for the user. They dont have to build wget from source.
---
---
> wget2 info for debian package

- ani-cli
> aria2 continue interrupted downloads

- ani-cli
Changed http agent from linux to windows in order to minimized browser fingerprinting
Enhanced privacy, since linux systems are easily browser fingerprintable. Certain that it will interfere with the rest of the code, I made a pull request to avoid changing it manual after each update.
---
---
> Http agent from linux to windows for privacy

- ani-cli
Hi bros, Change quality feature,everything working, cant confirm syncplay tho I dont have it
only 3 LOC :)))))
---
---
> Change quality #1006

- ani-cli
Hi guys just want to fix UX related issues
- the episodes are displayed to descending order which is usually not a good experience for users
- the menu should display the next episode option first followed by other relevant option and currently the quit option is displayed first after each episode play ends
PS: don't have syncplay so didn't test that.. apart from that everything is working
---
---
> Ani-cli UX Changes

- ani-cli
> fix: previous,next,replay bug

- ani-cli
> fix: remove --tls-max 1.2 bc of windows

- ani-cli
The "Specified quality not found, defaulting to best" message was missing a line-break causing the next message to appear on the same line.
I only added a /n to a string. The test I've done are marked below.
It appears my settings removed a trailing white-space as well. If that's a nuisance then sorry about that.
---
---
> fix: missing linebreak in quality-miss printf

- ani-cli
> fix: url change to allanime.to

- README.md
First off, congratulations for creating and maintaining this project!!
It's great and I really enjoy it!!
This pull request is simply to remove of two out-of-place forward slashes 
( / ) in README.md, in the install instructions for Windows and Termux.
I know it's a small detail, but it was never fixed, and those forward slashes 
cause the command to not execute properly, resulting in an useless 
command that should delete a folder, but does nothing instead.
In README.md - Install From Source,
for both Windows and Termux, 
the last command 'rm -rf /ani-cli' doesn't work,
since there is no 'ani-cli' folder in the '/' directory. 
It doesn't throw error because of the -f flag, but it 
also fails to remove the intended folder. This commit 
fixes this by removing the slash. Previous commands …
> Fix typo in install commands (win & termux) - README.md

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- ani-cli
- ani-cli.1
> fix: allanime graphql

- ani-cli
> fix: account for point episodes having multiple digits (e.g. 124.125)

- README.md
I copied the instructions on [nheko](https://nheko-reborn.github.io/repositories/) and replaced the name of the package.
Note that due to the forth regulation of the [guru regulations](https://wiki.gentoo.org/wiki/Project:GURU#The_regulations). People on stable will have to accept the unstable keyword for the package (which is not in the installation instructions)
> Added gentoo installation instructions

- README.md
Fixed a spelling issue in the readme
---
---
> fix: spelling error fom -> from

- .github/workflows/master.yml
- Bump the `actions/checkout` version to `v3` to fix the Node 12 deprecation warning displayed under Actions as the newer version uses Node 16.
---
> test: bump actions/checkout version to v3

- ani-cli
I normalized indentation to 4 spaces and ran ani-cli through shfmt, which mainly fixed some case statements
> style: consistent 4 space indentation + shfmt

- README.md
Governance
After a particularly disturbing toll from matrix this morning I'm proposing we officially close the matrix server.
~70% of messages coming from matrix are from users that also have active discord accounts.
20% from spammers and trolls in various intensities.
10% from actual legit users.
I'd rather alienate a small handful of free software maximalists than have another troll / crypto currency scammer / whatever.
> docs: remove matrix. discord only.

- ani-cli
> fix: history selection will be read from histfile again

- .gitignore
- README.md
- ani-cli
Pull Request Template
Type of change
[ ] Bug fix
[X] Feature
[ ] Documentation update
Description
added iSH detection, and used x-callback (Thanks [RubenPonce](https://github.com/RubenPonce) for telling me about that!) when iSH is detected. Oh, also adjusted readme to include iOS installation instructions.
Checklist
[X] any anime playing
[X] bumped version
---
[X] next, prev and replay work
[X] -c history and continue work
[X] -d downloads work
[X] -s syncplay works (Not on iOS)
[X] -q quality works
[X] -v vlc works
[X] -e select episode works
[X] -S select index works
[X] -r range selection works
[X] --dub both work
[X] all providers return links (not necessarily on a single anime, use debug mode to confirm)
---
[X] -h help info is up to date
[X] Readme is up to date
[X] Man page is up …
> Add iOS support to ani-cli

- ani-cli
add a `--non-interactive` and `-N` flag to disable the menu. Mentioned in #1104
[demo](https://user-images.githubusercontent.com/43939942/235757212-beb75f64-7c36-47d7-9937-bb9bc91b7a07.webm)
---
---
> feat: add non-interactive flag to disable menu

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- ani-cli
Undid a change that was merged in #993 but not documented (and thus deemed accidental): showing fzf during playing but not other launchers.
Modified the `change quality` menu point to display links that don't have a numeric resolution tag to help circumvent broken/slow links.
Also since I didn't do anything ground-breaking I'm willing to put the code to some testing and call it a major release. We have implemented a lot of small fixes lately, package maintainers should be able to package them now without problems. 
---
---
> Various fixes

- ani-cli
…or on the path for Windows
This fixes #1114.
This fix accounts for Syncplay being at either the default location (used by the Syncplay installer and the chocolatey package manager) or on the path.
If Syncplay doesn't exist in the default location, it will set `player_function` to "syncplay.exe", expecting it to come from the path.
---
---
> fix: account for syncplay in either default location or windows path

- ani-cli
…or on the path for Windows# Pull Request Template
*ramble here*
---
---
> (testing linter) account for syncplay in either default location or windows path

- README.md
- ani-cli
> docs: Add iOS uninstall instructions

- ani-cli
Disable loading aria2.conf file. to Disable `enable-rpc=true` from `${HOME}/.aria2/aria2.aria2.conf`
*ramble here*
---
---
> refactor: disable aria2 rpc

- ani-cli
- ani-cli.1
> fix: allanime scraping

- ani-cli
> feat: new providers + fix xxd posix compliance

- ani-cli
> fix: list number bug on mac

- ani-cli
> fix: nl for ep number <10

- ani-cli
NOTE :- Increasing the number will make the download faster but less stable and Decreasing the number will make download slower but stable.
and how auto clean `${HOME}/.cache/hls-temp` after the download is complete
*ramble here*
---
---
> refactor: hls Decreasing the number will make download slower but stable.

- README.md
- ani-cli
> fix: hex decryption

- ani-cli
- ani-cli.1
Our use of `cache_dir` didn't actually resemble cache in the traditional sense.
Cache would refer to semi-persistent storage that is reused between application runs.
In our use, we overwrote it on every run, making it working memory.
As such, it belongs in ram.
Ideally we can just concatenate right away.
This should fix #1178 and #1173, tho concatenation would be a more direct fix.
---
---
> fix: ani-cli cache_dir via mktemp (#1178, #1173)

- ani-cli
> refactor: mktemp POSIX violation

- ani-cli
- ani-cli.1
> feat: add rofi flag

- ani-cli
- ani-cli.1
> feat: proper non-interactive-mechanic

- README.md
- ani-cli
This update provides a simpler method for Windows users to use the application when utilizing WSL2. 
A current issue exists with syncplay. It does not work correctly. Simple way to reproduce it is to run it from WSL2 using:
```sh
"/mnt/c/Program Files (x86)/Syncplay/syncplay.exe"
```
It silently fails if a URL is specified(even during runtime), causing the window to close unexpectedly. A workaround for this is: (**not currently applied**)
```sh
cmd.exe /C "C:\Program Files (x86)\Syncplay\syncplay.exe" "$URL"
```
Moreover, using uname -s to switch cases for syncplay is insufficient and requires modification.
```sh
-s | --syncplay)
case "$(uname -s)" in
Darwin*) player_function="/Applications/Syncplay.app/Contents/MacOS/syncplay" ;;
MINGW* | *Msys)
export PATH="$PATH":"/c/Program Files …
```
> feat: add support for windows wsl2

- ani-cli
> refactor: remove -N flag in favor of -S + -e detection

- CONTRIBUTING.md
- shell.nix
Added nix dev shell env.
To use it go in the repo and use `nix-shell` in the dev shell you have all bin that ani-cli uses.
With arguments you can also add vlc, chromecast support and so on is commented in the `shell.nix` file
---
---
> test: add nix dev shell env

- README.md
For the newly released Android 14 update Termux's MPV intent seems to fail to execute unless you install the ``termux-am`` package as confirmed by me and these issues: 
- https://github.com/pystardust/ani-cli/issues/1206
- https://github.com/termux/termux-app/issues/3647#issuecomment-1763563028
---
---
> docs: Added android 14 fix in readme prior to #1206

- ani-cli
The check for [ $use_external_menu = 0 | 1 ] was made before the variable even gets a chance to be changed and use_external_menu was set to 0 just before that if ani-cli was started from a terminal.
BEFORE multi-selection (from the terminal with --rofi set) only worked if the env variable $ANI_CLI_EXTERNAL_MENU was set or ani-cli was not started from a terminal.
NOW multi-selection also works if the --rofi flag is set in via terminal, because the check takes place AFTER parcing command-line-arguments.
---
---
> fix: multi-selection support

- README.md
> docs: Update README.md to use now fixed FFmpeg

- ani-cli
Fix for the common windows issue "no results found"
---
---
> fix: curl in gitbash doesn't support `--cipher`

- ani-cli
> fix: removed last --cipher argument

- ani-cli
This PR fixes the slowness of script on windows during episode fetching, where the user waits upto ~30 seconds for it to fetch.
I have tested it on linux and with the help of some plebs, also on windows. Please test it thoroughtly on both platforms and also on other platform to maintain compatibility
---
---
> feat: script speed improvement on windows

- README.md
Makes ani-cli installation instructions for steamdeck work.
Also enables easy launch from Steam "game mode" 
Fix for this https://github.com/pystardust/ani-cli/issues/1268
---
---
> fix: Steam deck installation and .desktop fix

- ani-cli
- ani-cli.1
> feat: no-detach

- README.md
Steam Deck has no gnu patch preinstalled.
pacman -S patch wont work in a long term because the root partition is:
1. immutable (but can be set to be mutable)
2. reset with each steamOS update (at least from what i have heared)
Because we already add .local/bin to PATH, it make sense to install gnu patch in .local/bin.
> docs: Add gnu patch install script for Steam Deck

- ani-cli
Small syntax changes required to make this work on OpenBSD (and potentially other non-GNU/*BSD systems). Involved replacing `\n` and similar backslash-escaped characters with their literal representations (actual newline, tab). Should not break anything on other systems, checked briefly on NixOS, runs fine
---
---
> fix: making this work on OpenBS with non-GNU tools

- README.md
> docs: remove shell from mov-cli and change it's description

- .github/workflows/ani-cli.yml
- ani-cli
I briefly verified that the feature still works with naruto (finished), one piece (2 days) and boruto (multiple results)
> refactor: remove accidental awk and add ci-check for it

- ani-cli
Ani-Skip has been updated, with changed start arg
Ani-Skip has been updated, with changed start arg, so tiny fix for that.
I hope this is okay this way.
start arg now is -q [title] -e [episode]
---
---
> fix: adapt to ani-skip update

- ani-cli.1
I suppose this is just a little oversight. Should not require a version bump as only the manpage is affected.
---
---
> docs: removed duplicate entries from manpage

- ani-cli
Small fix for #1313, it didnt work correcly in continue mode.
I must have forgotten to test continue correcly after the last change in that PR, sorry about that.
---
---
> fix: ani-skip not working in continue

- ani-cli
- ani-cli.1
> feat: exit after play

- ani-cli
> refactor: Remove Dead Wixmp Provider

- README.md
Installation instructions for individual Linux distributions are already included, but it is not mentioned that ani-cli requires that the media player is installed on Windows (not in WSL). The reason for this is here: https://github.com/pystardust/ani-cli/issues/1266#issuecomment-1926945757.
> docs: add wsl installation instructions

- README.md
I added Tier 2 FreeBSD support using the linuxemu (aka Linux ABI)
which is very simple to setup.
---
---
> docs: added FreeBSD installation instructions

- ani-cli
fix: update outdated titles in history selection
*ramble here*
---
---
> fix: update title in history file

- ani-cli
Allows using --select-nth with --continue to select the anime when there's multiple to choose from.
This adds a check for --select-nth when using --continue to select the anime, so it can be done non-interactively.
Updated to work with the current code base. =)
---
---
> fix: allow using --select-nth with --continue

- ani-cli
- [X ] Bug fix
Ani-Cli originally checks for Steam Deck / SteamOS by checking for the default host name, which breaks the script if the host name is changed by the user. This fix checks for the kernel codename instead.
> fix: steamdeck kernel detection

- ani-cli
How the hell did this happen?
I couldn’t test sync play as I don’t have an actual PC on me atm.
Quality doesn’t work on the current version so it won’t work here either. This isn’t to fix that problem.
I don’t have ani-skip so I can’t test that but it should work.
couldn’t test no-detach cause I don’t have a PC on me rn. Again it should work
---
---
> fix: fix issue where a non-working Alt link gets used when on iSH

- ani-cli
> fix: support using non brew iina as a player on macos

- ani-cli
- ani-cli.1
> feat: initial logger support

- README.md
updated the FAQ to add "Can i change download folder? - Yes, set the `ANI_CLI_DOWNLOAD_DIR` to your desired location."
*ramble here*
---
---
> docs: explain how to change download folder in the FAQ

- .github/workflows/ani-cli.yml
- .github/workflows/inverse-ani.yml
- .github/workflows/version.yml
> ci: fix conflicting path and path ignore

- README.md
corrected a typo on line 554
*ramble here*
---
---
> docs: adjust formatting on readme line 554

- README.md
Adds [FastAnime](https://github.com/Benex254/FastAnime) to homies which is just a tool that aims to replicate the anime browser site experience in the terminal.
> docs: add fastanime to homies

- ani-cli
(done practically nothing)
---
---
> refactor: allanime url update + re-adding the wixmp provider

- ani-cli
Checks to see if the episode selected is in the list of scraped episodes available for that show and season. Updated error message to reflect result
Adds additional error messages as discussed in #1429. Previously, any time there was an error, it would always say "Episode not released!" which is not true sometimes. This happens in the case of an episode being released, but not pulling a source correctly (or source not available). This just adds a simple check to see if the $ep_no is in $ep_list. If it is and $episode is empty, it states that the episode is released, but no source available, else, it falls back to the current error message.
While I was here, I implemented 71zenith's suggestion in #1391 to fix issues with specifically Oshi No Ko's second season. It didn't quite work as …
> fix: Error logic and updated message and mis-escaped quotes

- ani-cli
Using $(uname -a | awk '{$2=""; print $0}') instead of just uname -a helps remove the hostname from the output. since hostname can vary between systems it may lead to incorrect OS detection. By stripping out the hostname case statement accurately matches the relevant OS identifiers.
In my system script not work properly because my hostname is "vaishakh" , because it contains "ish" the case identify my linux device as ios device and ani-cli failed to play the video.
---
---
> fix: remove hostname from uname output in OS detection

- README.md
- ani-cli
- hacking.md
*ramble here*
was bored
---
---
> docs: spell check

- README.md
> docs: fix dead links to dependencies

- ani-cli
> fix: range selection

- ani-cli
- ani-cli.1
On GNOME rofi doesn't receive keyboard input as it is not by default a normal window. Since I'm on Wayland I also tried the rofi-wayland package but it failed to launch because rofi on Wayland requires support for the layer shell protocol. Therefore I decided to implement the option inside ani-cli. The user can add the flag --normal-window (alongside --rofi) to pass -normal-window to rofi. I also added the possibility to set the environment variable ANI_CLI_EXTERNAL_MENU_NORMAL_WINDOW to make it happen always.
---
---
> feat: add possibility to display rofi menus as normal windows

- README.md
Add a mention of an IINA plugin to skip opening and ending sequences on animes. It works similarly to ani-skip but works seamlessly with IINA, without any config flags needed.
---
---
- All Providers: Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e (TV) (3 m3u8, 3 mp4, 1 fast4speed, 1 sharepoint)
- The examples of the help text
> docs: add IINA ani-skip to README.md

- ani-cli
A simple fix to make asynch-dns = false only apply to iOS
The items not marked don’t work on iOS (likely due to how you can only launch VLC with the link and nothing more)
also, this wasn’t tested on Mac OS as I do not have a Mac. It should work tho
---
- [C] `-e` (select episode) aka `-r` (range selection) works
---
- All Providers: Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e (TV) (3 m3u8, 3 mp4, 1 fast4speed, 1 sharepoint)
- The examples of the help text
> fix: Fix Mac OS downloading

- ani-cli
*ramble here*
---
---
- All Providers: Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e (TV) (3 m3u8, 3 mp4, 1 fast4speed, 1 sharepoint)
- The examples of the help text
> fix: ffmeg is retarded

- matrix.md
New matrix invite procedure utilising `knocking` feature.
---
---
- All Providers: Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e (TV) (3 m3u8, 3 mp4, 1 fast4speed, 1 sharepoint)
- The examples of the help text
> docs: New matrix invite procedure
